import {h} from 'snabbdom/h'
import ResultDataView from '../../resultdataview'
import WizardView from '../wizardview'

export default (state, send) => {
  // TODO: support result arrays
  return WizardView(
    state, 
    send, 
    'Get Result Label', 
    "Here you must select how to go about extracting a label from the data generated by the PowerShell command. You want this to be a unique identifier for this result view, as well as a title that gives the user an idea of what they're looking at. Most of these are assuming the data is converted to JSON, if that isn't the case, use the 'text' value type. To find out what keys exist in the JSON output, try running your command in a PowerShell console piped to the ConvertTo-JSON cmdlet. You should input the key exactly as it appears in the JSON. The exceptions are the static type which ignores the command's output, and the aforementioned text type.",
    h('div.column', ResultDataView(
      state,
      send,
      state.action.wizard.funcName,
      state.action.json.functions[state.action.wizard.funcName].result.label,
      `${state.action.filename}-${state.action.wizard.funcName}-action-result-label`,
      ['label']
    ))
    // TODO: validate result data
  )
}